/*
 * #%L
 * GwtMaterial
 * %%
 * Copyright (C) 2015 - 2016 GwtMaterialDesign
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package gwt.material.design.lite.client.constants;

import gwt.material.design.lite.client.utils.helper.EnumHelper;

/**
 * Color constants.
 *
 * @author kevzlou7979
 */
public enum Color implements CssType {
    DEFAULT(""),
    BLACK("mdl-color--black"),
    WHITE("mdl-color--white"),
    // Design
    PRIMARY("mdl-color--primary"),
    PRIMARY_CONTRAST("mdl-color--primary-contrast"),
    PRIMARY_DARK("mdl-color--primary-dark"),
    ACCENT("mdl-color--accent"),
    ACCENT_CONTRAST("mdl-color--accent-contrast"),
    TEXT_PRIMARY("mdl-color-text--primary"),
    TEXT_PRIMARY_CONTRAST("mdl-color-text--primary-contrast"),
    TEXT_PRIMARY_DARK("mdl-color-text--primary-dark"),
    TEXT_ACCENT("mdl-color-text--accent"),
    TEXT_ACCENT_CONTRAST("mdl-color-text--accent-contrast"),
    // Blue Grey
	BLUE_GREY_LIGHTEN_5("mdl-color--blue-grey-50"),
    BLUE_GREY_LIGHTEN_4("mdl-color--blue-grey-100"),
    BLUE_GREY_LIGHTEN_3("mdl-color--blue-grey-200"),
    BLUE_GREY_LIGHTEN_2("mdl-color--blue-grey-300"),
    BLUE_GREY_LIGHTEN_1("mdl-color--blue-grey-400"),
    BLUE_GREY("mdl-color--blue-grey-500"),
    BLUE_GREY_DARKEN_1("mdl-color--blue-grey-600"),
    BLUE_GREY_DARKEN_2("mdl-color--blue-grey-700"),
    BLUE_GREY_DARKEN_3("mdl-color--blue-grey-800"),
    BLUE_GREY_DARKEN_4("mdl-color--blue-grey-900"),
    // Grey
	GREY_LIGHTEN_5("mdl-color--grey-50"),
    GREY_LIGHTEN_4("mdl-color--grey-100"),
    GREY_LIGHTEN_3("mdl-color--grey-200"),
    GREY_LIGHTEN_2("mdl-color--grey-300"),
    GREY_LIGHTEN_1("mdl-color--grey-400"),
    GREY("mdl-color--grey-500"),
    GREY_DARKEN_1("mdl-color--grey-600"),
    GREY_DARKEN_2("mdl-color--grey-700"),
    GREY_DARKEN_3("mdl-color--grey-800"),
    GREY_DARKEN_4("mdl-color--grey-900"),
    // Brown
	BROWN_LIGHTEN_5("mdl-color--brown-50"),
    BROWN_LIGHTEN_4("mdl-color--brown-100"),
    BROWN_LIGHTEN_3("mdl-color--brown-200"),
    BROWN_LIGHTEN_2("mdl-color--brown-300"),
    BROWN_LIGHTEN_1("mdl-color--brown-400"),
    BROWN("mdl-color--brown-500"),
    BROWN_DARKEN_1("mdl-color--brown-600"),
    BROWN_DARKEN_2("mdl-color--brown-700"),
    BROWN_DARKEN_3("mdl-color--brown-800"),
    BROWN_DARKEN_4("mdl-color--brown-900"),
    // Deep Orange
	DEEP_ORANGE_LIGHTEN_5("mdl-color--deep-orange-50"),
    DEEP_ORANGE_LIGHTEN_4("mdl-color--deep-orange-100"),
    DEEP_ORANGE_LIGHTEN_3("mdl-color--deep-orange-200"),
    DEEP_ORANGE_LIGHTEN_2("mdl-color--deep-orange-300"),
    DEEP_ORANGE_LIGHTEN_1("mdl-color--deep-orange-400"),
    DEEP_ORANGE("mdl-color--deep-orange-500"),
    DEEP_ORANGE_DARKEN_1("mdl-color--deep-orange-600"),
    DEEP_ORANGE_DARKEN_2("mdl-color--deep-orange-700"),
    DEEP_ORANGE_DARKEN_3("mdl-color--deep-orange-800"),
    DEEP_ORANGE_DARKEN_4("mdl-color--deep-orange-900"),
    DEEP_ORANGE_ACCENT_1("mdl-color--deep-orange-A100"),
    DEEP_ORANGE_ACCENT_2("mdl-color--deep-orange-A200"),
    DEEP_ORANGE_ACCENT_3("mdl-color--deep-orange-A300"),
    DEEP_ORANGE_ACCENT_4("mdl-color--deep-orange-A400"),
    // Orange
	ORANGE_LIGHTEN_5("mdl-color--orange-50"),
    ORANGE_LIGHTEN_4("mdl-color--orange-100"),
    ORANGE_LIGHTEN_3("mdl-color--orange-200"),
    ORANGE_LIGHTEN_2("mdl-color--orange-300"),
    ORANGE_LIGHTEN_1("mdl-color--orange-400"),
    ORANGE("mdl-color--orange-500"),
    ORANGE_DARKEN_1("mdl-color--orange-600"),
    ORANGE_DARKEN_2("mdl-color--orange-700"),
    ORANGE_DARKEN_3("mdl-color--orange-800"),
    ORANGE_DARKEN_4("mdl-color--orange-900"),
    ORANGE_ACCENT_1("mdl-color--orange-A100"),
    ORANGE_ACCENT_2("mdl-color--orange-A200"),
    ORANGE_ACCENT_3("mdl-color--orange-A300"),
    ORANGE_ACCENT_4("mdl-color--orange-A400"),
    // amber
	AMBER_LIGHTEN_5("mdl-color--amber-50"),
    AMBER_LIGHTEN_4("mdl-color--amber-100"),
    AMBER_LIGHTEN_3("mdl-color--amber-200"),
    AMBER_LIGHTEN_2("mdl-color--amber-300"),
    AMBER_LIGHTEN_1("mdl-color--amber-400"),
    AMBER("mdl-color--amber-500"),
    AMBER_DARKEN_1("mdl-color--amber-600"),
    AMBER_DARKEN_2("mdl-color--amber-700"),
    AMBER_DARKEN_3("mdl-color--amber-800"),
    AMBER_DARKEN_4("mdl-color--amber-900"),
    AMBER_ACCENT_1("mdl-color--amber-A100"),
    AMBER_ACCENT_2("mdl-color--amber-A200"),
    AMBER_ACCENT_3("mdl-color--amber-A300"),
    AMBER_ACCENT_4("mdl-color--amber-A400"),
    // Yellow
	YELLOW_LIGHTEN_5("mdl-color--yellow-50"),
    YELLOW_LIGHTEN_4("mdl-color--yellow-100"),
    YELLOW_LIGHTEN_3("mdl-color--yellow-200"),
    YELLOW_LIGHTEN_2("mdl-color--yellow-300"),
    YELLOW_LIGHTEN_1("mdl-color--yellow-400"),
    YELLOW("mdl-color--yellow-500"),
    YELLOW_DARKEN_1("mdl-color--yellow-600"),
    YELLOW_DARKEN_2("mdl-color--yellow-700"),
    YELLOW_DARKEN_3("mdl-color--yellow-800"),
    YELLOW_DARKEN_4("mdl-color--yellow-900"),
    YELLOW_ACCENT_1("mdl-color--yellow-A100"),
    YELLOW_ACCENT_2("mdl-color--yellow-A200"),
    YELLOW_ACCENT_3("mdl-color--yellow-A300"),
    YELLOW_ACCENT_4("mdl-color--yellow-A400"),
    // Lime
	LIME_LIGHTEN_5("mdl-color--lime-50"),
    LIME_LIGHTEN_4("mdl-color--lime-100"),
    LIME_LIGHTEN_3("mdl-color--lime-200"),
    LIME_LIGHTEN_2("mdl-color--lime-300"),
    LIME_LIGHTEN_1("mdl-color--lime-400"),
    LIME("mdl-color--lime-500"),
    LIME_DARKEN_1("mdl-color--lime-600"),
    LIME_DARKEN_2("mdl-color--lime-700"),
    LIME_DARKEN_3("mdl-color--lime-800"),
    LIME_DARKEN_4("mdl-color--lime-900"),
    LIME_ACCENT_1("mdl-color--lime-A100"),
    LIME_ACCENT_2("mdl-color--lime-A200"),
    LIME_ACCENT_3("mdl-color--lime-A300"),
    LIME_ACCENT_4("mdl-color--lime-A400"),
    // Light Green
	LIGHT_GREEN_LIGHTEN_5("mdl-color--light-green-50"),
    LIGHT_GREEN_LIGHTEN_4("mdl-color--light-green-100"),
    LIGHT_GREEN_LIGHTEN_3("mdl-color--light-green-200"),
    LIGHT_GREEN_LIGHTEN_2("mdl-color--light-green-300"),
    LIGHT_GREEN_LIGHTEN_1("mdl-color--light-green-400"),
    LIGHT_GREEN("mdl-color--light-green-500"),
    LIGHT_GREEN_DARKEN_1("mdl-color--light-green-600"),
    LIGHT_GREEN_DARKEN_2("mdl-color--light-green-700"),
    LIGHT_GREEN_DARKEN_3("mdl-color--light-green-800"),
    LIGHT_GREEN_DARKEN_4("mdl-color--light-green-900"),
    LIGHT_GREEN_ACCENT_1("mdl-color--light-green-A100"),
    LIGHT_GREEN_ACCENT_2("mdl-color--light-green-A200"),
    LIGHT_GREEN_ACCENT_3("mdl-color--light-green-A300"),
    LIGHT_GREEN_ACCENT_4("mdl-color--light-green-A400"),
    // Green
	GREEN_LIGHTEN_5("mdl-color--green-50"),
    GREEN_LIGHTEN_4("mdl-color--green-100"),
    GREEN_LIGHTEN_3("mdl-color--green-200"),
    GREEN_LIGHTEN_2("mdl-color--green-300"),
    GREEN_LIGHTEN_1("mdl-color--green-400"),
    GREEN("mdl-color--green-500"),
    GREEN_DARKEN_1("mdl-color--green-600"),
    GREEN_DARKEN_2("mdl-color--green-700"),
    GREEN_DARKEN_3("mdl-color--green-800"),
    GREEN_DARKEN_4("mdl-color--green-900"),
    GREEN_ACCENT_1("mdl-color--green-A100"),
    GREEN_ACCENT_2("mdl-color--green-A200"),
    GREEN_ACCENT_3("mdl-color--green-A300"),
    GREEN_ACCENT_4("mdl-color--green-A400"),
    // Teal
	TEAL_LIGHTEN_5("mdl-color--teal-50"),
    TEAL_LIGHTEN_4("mdl-color--teal-100"),
    TEAL_LIGHTEN_3("mdl-color--teal-200"),
    TEAL_LIGHTEN_2("mdl-color--teal-300"),
    TEAL_LIGHTEN_1("mdl-color--teal-400"),
    TEAL("mdl-color--teal-500"),
    TEAL_DARKEN_1("mdl-color--teal-600"),
    TEAL_DARKEN_2("mdl-color--teal-700"),
    TEAL_DARKEN_3("mdl-color--teal-800"),
    TEAL_DARKEN_4("mdl-color--teal-900"),
    TEAL_ACCENT_1("mdl-color--teal-A100"),
    TEAL_ACCENT_2("mdl-color--teal-A200"),
    TEAL_ACCENT_3("mdl-color--teal-A300"),
    TEAL_ACCENT_4("mdl-color--teal-A400"),
    // Cyan
	CYAN_LIGHTEN_5("mdl-color--cyan-50"),
    CYAN_LIGHTEN_4("mdl-color--cyan-100"),
    CYAN_LIGHTEN_3("mdl-color--cyan-200"),
    CYAN_LIGHTEN_2("mdl-color--cyan-300"),
    CYAN_LIGHTEN_1("mdl-color--cyan-400"),
    CYAN("mdl-color--cyan-500"),
    CYAN_DARKEN_1("mdl-color--cyan-600"),
    CYAN_DARKEN_2("mdl-color--cyan-700"),
    CYAN_DARKEN_3("mdl-color--cyan-800"),
    CYAN_DARKEN_4("mdl-color--cyan-900"),
    CYAN_ACCENT_1("mdl-color--cyan-A100"),
    CYAN_ACCENT_2("mdl-color--cyan-A200"),
    CYAN_ACCENT_3("mdl-color--cyan-A300"),
    CYAN_ACCENT_4("mdl-color--cyan-A400"),
    // Light Blue
	LIGHT_BLUE_LIGHTEN_5("mdl-color--light-blue-50"),
    LIGHT_BLUE_LIGHTEN_4("mdl-color--light-blue-100"),
    LIGHT_BLUE_LIGHTEN_3("mdl-color--light-blue-200"),
    LIGHT_BLUE_LIGHTEN_2("mdl-color--light-blue-300"),
    LIGHT_BLUE_LIGHTEN_1("mdl-color--light-blue-400"),
    LIGHT_BLUE("mdl-color--light-blue-500"),
    LIGHT_BLUE_DARKEN_1("mdl-color--light-blue-600"),
    LIGHT_BLUE_DARKEN_2("mdl-color--light-blue-700"),
    LIGHT_BLUE_DARKEN_3("mdl-color--light-blue-800"),
    LIGHT_BLUE_DARKEN_4("mdl-color--light-blue-900"),
    LIGHT_BLUE_ACCENT_1("mdl-color--light-blue-A100"),
    LIGHT_BLUE_ACCENT_2("mdl-color--light-blue-A200"),
    LIGHT_BLUE_ACCENT_3("mdl-color--light-blue-A300"),
    LIGHT_BLUE_ACCENT_4("mdl-color--light-blue-A400"),
    // Blue
	BLUE_LIGHTEN_5("mdl-color--blue-50"),
    BLUE_LIGHTEN_4("mdl-color--blue-100"),
    BLUE_LIGHTEN_3("mdl-color--blue-200"),
    BLUE_LIGHTEN_2("mdl-color--blue-300"),
    BLUE_LIGHTEN_1("mdl-color--blue-400"),
    BLUE("mdl-color--blue-500"),
    BLUE_DARKEN_1("mdl-color--blue-600"),
    BLUE_DARKEN_2("mdl-color--blue-700"),
    BLUE_DARKEN_3("mdl-color--blue-800"),
    BLUE_DARKEN_4("mdl-color--blue-900"),
    BLUE_ACCENT_1("mdl-color--blue-A100"),
    BLUE_ACCENT_2("mdl-color--blue-A200"),
    BLUE_ACCENT_3("mdl-color--blue-A300"),
    BLUE_ACCENT_4("mdl-color--blue-A400"),
    // Indigo
	INDIGO_LIGHTEN_5("mdl-color--indigo-50"),
    INDIGO_LIGHTEN_4("mdl-color--indigo-100"),
    INDIGO_LIGHTEN_3("mdl-color--indigo-200"),
    INDIGO_LIGHTEN_2("mdl-color--indigo-300"),
    INDIGO_LIGHTEN_1("mdl-color--indigo-400"),
    INDIGO("mdl-color--indigo-500"),
    INDIGO_DARKEN_1("mdl-color--indigo-600"),
    INDIGO_DARKEN_2("mdl-color--indigo-700"),
    INDIGO_DARKEN_3("mdl-color--indigo-800"),
    INDIGO_DARKEN_4("mdl-color--indigo-900"),
    INDIGO_ACCENT_1("mdl-color--indigo-A100"),
    INDIGO_ACCENT_2("mdl-color--indigo-A200"),
    INDIGO_ACCENT_3("mdl-color--indigo-A300"),
    INDIGO_ACCENT_4("mdl-color--indigo-A400"),
    // Deep Purple
	DEEP_PURPLE_LIGHTEN_5("mdl-color--deep-purple-50"),
    DEEP_PURPLE_LIGHTEN_4("mdl-color--deep-purple-100"),
    DEEP_PURPLE_LIGHTEN_3("mdl-color--deep-purple-200"),
    DEEP_PURPLE_LIGHTEN_2("mdl-color--deep-purple-300"),
    DEEP_PURPLE_LIGHTEN_1("mdl-color--deep-purple-400"),
    DEEP_PURPLE("mdl-color--deep-purple-500"),
    DEEP_PURPLE_DARKEN_1("mdl-color--deep-purple-600"),
    DEEP_PURPLE_DARKEN_2("mdl-color--deep-purple-700"),
    DEEP_PURPLE_DARKEN_3("mdl-color--deep-purple-800"),
    DEEP_PURPLE_DARKEN_4("mdl-color--deep-purple-900"),
    DEEP_PURPLE_ACCENT_1("mdl-color--deep-purple-A100"),
    DEEP_PURPLE_ACCENT_2("mdl-color--deep-purple-A200"),
    DEEP_PURPLE_ACCENT_3("mdl-color--deep-purple-A300"),
    DEEP_PURPLE_ACCENT_4("mdl-color--deep-purple-A400"),
    // Purple
	PURPLE_LIGHTEN_5("mdl-color--purple-50"),
    PURPLE_LIGHTEN_4("mdl-color--purple-100"),
    PURPLE_LIGHTEN_3("mdl-color--purple-200"),
    PURPLE_LIGHTEN_2("mdl-color--purple-300"),
    PURPLE_LIGHTEN_1("mdl-color--purple-400"),
    PURPLE("mdl-color--purple-500"),
    PURPLE_DARKEN_1("mdl-color--purple-600"),
    PURPLE_DARKEN_2("mdl-color--purple-700"),
    PURPLE_DARKEN_3("mdl-color--purple-800"),
    PURPLE_DARKEN_4("mdl-color--purple-900"),
    PURPLE_ACCENT_1("mdl-color--purple-A100"),
    PURPLE_ACCENT_2("mdl-color--purple-A200"),
    PURPLE_ACCENT_3("mdl-color--purple-A300"),
    PURPLE_ACCENT_4("mdl-color--purple-A400"),
    // Pink
	PINK_LIGHTEN_5("mdl-color--pink-50"),
    PINK_LIGHTEN_4("mdl-color--pink-100"),
    PINK_LIGHTEN_3("mdl-color--pink-200"),
    PINK_LIGHTEN_2("mdl-color--pink-300"),
    PINK_LIGHTEN_1("mdl-color--pink-400"),
    PINK("mdl-color--pink-500"),
    PINK_DARKEN_1("mdl-color--pink-600"),
    PINK_DARKEN_2("mdl-color--pink-700"),
    PINK_DARKEN_3("mdl-color--pink-800"),
    PINK_DARKEN_4("mdl-color--pink-900"),
    PINK_ACCENT_1("mdl-color--pink-A100"),
    PINK_ACCENT_2("mdl-color--pink-A200"),
    PINK_ACCENT_3("mdl-color--pink-A300"),
    PINK_ACCENT_4("mdl-color--pink-A400"),
    // Red
    RED_LIGHTEN_5("mdl-color--red-50"),
    RED_LIGHTEN_4("mdl-color--red-100"),
    RED_LIGHTEN_3("mdl-color--red-200"),
    RED_LIGHTEN_2("mdl-color--red-300"),
    RED_LIGHTEN_1("mdl-color--red-400"),
    RED("mdl-color--red-500"),
    RED_DARKEN_1("mdl-color--red-600"),
    RED_DARKEN_2("mdl-color--red-700"),
    RED_DARKEN_3("mdl-color--red-800"),
    RED_DARKEN_4("mdl-color--red-900"),
    RED_ACCENT_1("mdl-color--red-A100"),
    RED_ACCENT_2("mdl-color--red-A200"),
    RED_ACCENT_3("mdl-color--red-A300"),
    RED_ACCENT_4("mdl-color--red-A400");

    private final String cssClass;

    Color(final String cssClass) {
        this.cssClass = cssClass;
    }

    @Override
    public String getCssName() {
        return cssClass;
    }

    public static Color fromStyleName(final String styleName) {
        return EnumHelper.fromStyleName(styleName, Color.class, Color.DEFAULT);
    }
}
